# Score 67.464%

In [1]:
import os
os.sys.path.append("/Users/pbezuhov/git/custom_libraries/")
import main as m

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Imputer

training_data = pd.read_csv('../data/titanic/train.csv')
testing_data = pd.read_csv('../data/titanic/test.csv')

In [3]:
mod_training_data = training_data.dropna()
mod_training_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
predictors = ['Age', 'Sex', 'Pclass', 'SibSp', 'Fare', 'Parch']

y = mod_training_data.Survived
x = mod_training_data[predictors]
ohe_x = pd.get_dummies(x)

train_x, val_x, train_y, val_y = train_test_split(ohe_x.as_matrix(), y.as_matrix(), test_size=0.20)

In [5]:
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression

pipeline = make_pipeline(Imputer(), LogisticRegression())

pipeline.fit(train_x, train_y)

Pipeline(memory=None,
     steps=[('imputer', Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)), ('logisticregression', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))])

In [6]:
validation_results = pipeline.predict(val_x)

val_results_to_binary = m.to_discrete(list(validation_results), 0, 1)

# print("Mean Absolute Error : " + str(mean_absolute_error(validation_results, val_y)))
print("Percent correct : " + str(m.percent_right(val_results_to_binary, val_y)))

Percent correct : 0.8378378378378378

In [7]:
test_x = testing_data[predictors]
test_x = pd.get_dummies(test_x)
test_x

      Age  Pclass  SibSp      Fare  Parch  Sex_female  Sex_male
0    34.5       3      0    7.8292      0           0         1
1    47.0       3      1    7.0000      0           1         0
2    62.0       2      0    9.6875      0           0         1
3    27.0       3      0    8.6625      0           0         1
4    22.0       3      1   12.2875      1           1         0
5    14.0       3      0    9.2250      0           0         1
6    30.0       3      0    7.6292      0           1         0
7    26.0       2      1   29.0000      1           0         1
8    18.0       3      0    7.2292      0           1         0
9    21.0       3      2   24.1500      0           0         1
10    NaN       3      0    7.8958      0           0         1
11   46.0       1      0   26.0000      0           0         1
12   23.0       1      1   82.2667      0           1         0
13   63.0       2      1   26.0000      0           0         1
14   47.0       1      1   61.1750      0           1         0
15   24.0       2      1   27.7208      0           1         0
16   35.0       2      0   12.3500      0           0         1
17   21.0       3      0    7.2250      0           0         1
18   27.0       3      1    7.9250      0           1         0
19   45.0       3      0    7.2250      0           1         0
20   55.0       1      1   59.4000      0           0         1
21    9.0       3      0    3.1708      1           0         1
22    NaN       1      0   31.6833      0           1         0
23   21.0       1      0   61.3792      1           0         1
24   48.0       1      1  262.3750      3           1         0
25   50.0       3      1   14.5000      0           0         1
26   22.0       1      0   61.9792      1           1         0
27   22.5       3      0    7.2250      0           0         1
28   41.0       1      0   30.5000      0           0         1
29    NaN       3      2   21.6792      0           0         1
..    ...     ...    ...       ...    ...         ...       ...
388  21.0       3      0    7.7500      0           0         1
389   6.0       3      3   21.0750      1           0         1
390  23.0       1      0   93.5000      0           0         1
391  51.0       1      0   39.4000      1           1         0
392  13.0       3      0   20.2500      2           0         1
393  47.0       2      0   10.5000      0           0         1
394  29.0       3      3   22.0250      1           0         1
395  18.0       1      1   60.0000      0           1         0
396  24.0       3      0    7.2500      0           0         1
397  48.0       1      1   79.2000      1           1         0
398  22.0       3      0    7.7750      0           0         1
399  31.0       3      0    7.7333      0           0         1
400  30.0       1      0  164.8667      0           1         0
401  38.0       2      1   21.0000      0           0         1
402  22.0       1      0   59.4000      1           1         0
403  17.0       1      0   47.1000      0           0         1
404  43.0       1      1   27.7208      0           0         1
405  20.0       2      0   13.8625      0           0         1
406  23.0       2      1   10.5000      0           0         1
407  50.0       1      1  211.5000      1           0         1
408   NaN       3      0    7.7208      0           1         0
409   3.0       3      1   13.7750      1           1         0
410   NaN       3      0    7.7500      0           1         0
411  37.0       1      1   90.0000      0           1         0
412  28.0       3      0    7.7750      0           1         0
413   NaN       3      0    8.0500      0           0         1
414  39.0       1      0  108.9000      0           1         0
415  38.5       3      0    7.2500      0           0         1
416   NaN       3      0    8.0500      0           0         1
417   NaN       3      1   22.3583      1           0         1

[418 rows x 7 columns]

In [8]:
predictions = pipeline.predict(test_x.as_matrix())

In [9]:
columns = ["PassengerId", "Survived"]
ids = testing_data['PassengerId'].as_matrix()
data = list(zip(ids, list(predictions)))
m.save_file('/Users/pbezuhov/git/Kaggle/submissions/titanic/5_regression.csv', data, columns)