# Score 62.679%

In [1]:
import os
os.sys.path.append("/Users/pbezuhov/git/custom_libraries/")
import main as m

In [14]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Imputer

from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestRegressor

training_data = pd.read_csv('../data/titanic/train.csv')
testing_data = pd.read_csv('../data/titanic/test.csv')

In [15]:
mod_training_data = training_data.dropna()
mod_training_data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [16]:
predictors = ['Age', 'Sex', 'Pclass', 'SibSp', 'Fare', 'Parch', 'Cabin']

y = mod_training_data.Survived
x = mod_training_data[predictors]

In [17]:
def clean_cabin(x):
    try:
        return x[0]
    except TypeError:
        return "None"
    
x.Cabin = x.Cabin.apply(clean_cabin)

/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:3110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [18]:
ohe_x = pd.get_dummies(x)

train_x, val_x, train_y, val_y = train_test_split(ohe_x.as_matrix(), y.as_matrix(), test_size=0.20)

In [19]:
pipeline = make_pipeline(Imputer(), RandomForestRegressor(100, oob_score=True, random_state=42, min_samples_leaf=5))

pipeline.fit(train_x, train_y)

Pipeline(memory=None,
     steps=[('imputer', Imputer(axis=0, copy=True, missing_values='NaN', strategy='mean', verbose=0)), ('randomforestregressor', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_s...estimators=100, n_jobs=1,
           oob_score=True, random_state=42, verbose=0, warm_start=False))])

In [20]:
validation_results = pipeline.predict(val_x)

val_results_to_binary = m.to_discrete(list(validation_results), 0, 1)

# print("Mean Absolute Error : " + str(mean_absolute_error(validation_results, val_y)))
print("Percent correct : " + str(m.percent_right(val_results_to_binary, val_y)))

Percent correct : 0.7837837837837838

In [21]:
test_x = testing_data[predictors]
test_x.Cabin = test_x.Cabin.apply(clean_cabin)
test_x = pd.get_dummies(test_x)
test_x

/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:3110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

,Age,Pclass,SibSp,Fare,Parch,Sex_female,Sex_male,Cabin_A,Cabin_B,Cabin_C,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_None
0,34.5,3,0,7.8292,0,0,1,0,0,0,0,0,0,0,1
1,47.0,3,1,7.0000,0,1,0,0,0,0,0,0,0,0,1
2,62.0,2,0,9.6875,0,0,1,0,0,0,0,0,0,0,1
3,27.0,3,0,8.6625,0,0,1,0,0,0,0,0,0,0,1
4,22.0,3,1,12.2875,1,1,0,0,0,0,0,0,0,0,1
5,14.0,3,0,9.2250,0,0,1,0,0,0,0,0,0,0,1
6,30.0,3,0,7.6292,0,1,0,0,0,0,0,0,0,0,1
7,26.0,2,1,29.0000,1,0,1,0,0,0,0,0,0,0,1
8,18.0,3,0,7.2292,0,1,0,0,0,0,0,0,0,0,1
9,21.0,3,2,24.1500,0,0,1,0,0,0,0,0,0,0,1
10,NaN,3,0,7.8958,0,0,1,0,0,0,0,0,0,0,1
11,46.0,1,0,26.0000,0,0,1,0,0,0,0,0,0,0,1
12,23.0,1,1,82.2667,0,1,0,0,1,0,0,0,0,0,0
13,63.0,2,1,26.0000,0,0,1,0,0,0,0,0,0,0,1
14,47.0,1,1,61.1750,0,1,0,0,0,0,0,1,0,0,0
15,24.0,2,1,27.7208,0,1,0,0,0,0,0,0,0,0,1
16,35.0,2,0,12.3500,0,0,1,0,0,0,0,0,0,0,1
17,21.0,3,0,7.2250,0,0,1,0,0,0,0,0,0,0,1
18,27.0,3,1,7.9250,0,1,0,0,0,0,0,0,0,0,1
19,45.0,3,0,7.2250,0,1,0,0,0,0,0,0,0,0,1
20,55.0,1,1,59.4000,0,0,1,0,0,0,0,0,0,0,1
21,9.0,3,0,3.1708,1,0,1,0,0,0,0,0,0,0,1
22,NaN,1,0,31.6833,0,1,0,0,0,0,0,0,0,0,1
23,21.0,1,0,61.3792,1,0,1,0,0,0,0,0,0,0,1
24,48.0,1,1,262.3750,3,1,0,0,1,0,0,0,0,0,0
25,50.0,3,1,14.5000,0,0,1,0,0,0,0,0,0,0,1
26,22.0,1,0,61.9792,1,1,0,0,1,0,0,0,0,0,0
27,22.5,3,0,7.2250,0,0,1,0,0,0,0,0,0,0,1
28,41.0,1,0,30.5000,0,0,1,1,0,0,0,0,0,0,0
29,NaN,3,2,21.6792,0,0,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388,21.0,3,0,7.7500,0,0,1,0,0,0,0,0,0,0,1
389,6.0,3,3,21.0750,1,0,1,0,0,0,0,0,0,0,1
390,23.0,1,0,93.5000,0,0,1,0,1,0,0,0,0,0,0
391,51.0,1,0,39.4000,1,1,0,0,0,0,1,0,0,0,0
392,13.0,3,0,20.2500,2,0,1,0,0,0,0,0,0,0,1
393,47.0,2,0,10.5000,0,0,1,0,0,0,0,0,0,0,1
394,29.0,3,3,22.0250,1,0,1,0,0,0,0,0,0,0,1
395,18.0,1,1,60.0000,0,1,0,0,0,1,0,0,0,0,0
396,24.0,3,0,7.2500,0,0,1,0,0,0,0,0,0,0,1
397,48.0,1,1,79.2000,1,1,0,0,1,0,0,0,0,0,0
398,22.0,3,0,7.7750,0,0,1,0,0,0,0,0,0,0,1
399,31.0,3,0,7.7333,0,0,1,0,0,0,0,0,0,0,1
400,30.0,1,0,164.8667,0,1,0,0,0,1,0,0,0,0,0
401,38.0,2,1,21.0000,0,0,1,0,0,0,0,0,0,0,1
402,22.0,1,0,59.4000,1,1,0,0,0,0,0,0,0,0,1
403,17.0,1,0,47.1000,0,0,1,0,0,0,0,0,0,0,1
404,43.0,1,1,27.7208,0,0,1,0,0,0,1,0,0,0,0
405,20.0,2,0,13.8625,0,0,1,0,0,0,1,0,0,0,0
406,23.0,2,1,10.5000,0,0,1,0,0,0,0,0,0,0,1
407,50.0,1,1,211.5000,1,0,1,0,0,1,0,0,0,0,0
408,NaN,3,0,7.7208,0,1,0,0,0,0,0,0,0,0,1
409,3.0,3,1,13.7750,1,1,0,0,0,0,0,0,0,0,1
410,NaN,3,0,7.7500,0,1,0,0,0,0,0,0,0,0,1
411,37.0,1,1,90.0000,0,1,0,0,0,1,0,0,0,0,0
412,28.0,3,0,7.7750,0,1,0,0,0,0,0,0,0,0,1
413,NaN,3,0,8.0500,0,0,1,0,0,0,0,0,0,0,1
414,39.0,1,0,108.9000,0,1,0,0,0,1,0,0,0,0,0
415,38.5,3,0,7.2500,0,0,1,0,0,0,0,0,0,0,1
416,NaN,3,0,8.0500,0,0,1,0,0,0,0,0,0,0,1
417,NaN,3,1,22.3583,1,0,1,0,0,0,0,0,0,0,1

In [28]:
predictions = pipeline.predict(test_x.as_matrix())
predictions = m.to_discrete(predictions, 0, 1)
predictions = predictions.astype(int)

In [29]:
columns = ["PassengerId", "Survived"]
ids = testing_data['PassengerId'].as_matrix()
data = list(zip(ids, list(predictions)))
m.save_file('/Users/pbezuhov/git/Kaggle/submissions/titanic/8_fine_tuned_rfr.csv', data, columns)